-- CreateTable
CREATE TABLE "Umowa" (
    "id" SERIAL NOT NULL,
    "handlowiec" TEXT NOT NULL,
    "dataPodpisania" TIMESTAMP(3) NOT NULL,
    "numerUmowy" TEXT NOT NULL,
    "imieNazwisko" TEXT NOT NULL,
    "telefon" TEXT NOT NULL,
    "ulica" TEXT NOT NULL,
    "miejscowosc" TEXT NOT NULL,
    "kodPocztowy" TEXT NOT NULL,
    "powiat" TEXT NOT NULL,
    "wojewodztwo" TEXT NOT NULL,
    "rodzajKlienta" TEXT NOT NULL,
    "peselNip" TEXT NOT NULL,
    "dowod" TEXT NOT NULL,
    "tel2" TEXT,
    "kontaktowyTel" TEXT,
    "email" TEXT,
    "operatorOsd" TEXT NOT NULL,
    "czyWlascicielLicznika" TEXT NOT NULL,
    "adresImie" TEXT NOT NULL,
    "adresUlica" TEXT NOT NULL,
    "adresNrDomu" TEXT NOT NULL,
    "adresMiejscowosc" TEXT NOT NULL,
    "adresKodPocztowy" TEXT NOT NULL,
    "adresPowiat" TEXT NOT NULL,
    "adresWojewodztwo" TEXT NOT NULL,
    "czyPosiadaInstalacje" TEXT NOT NULL,
    "miejsceInstalacji" TEXT,
    "miUlica" TEXT,
    "miNrDomu" TEXT,
    "miMiejscowosc" TEXT,
    "miKod" TEXT,
    "miPowiat" TEXT,
    "miWojewodztwo" TEXT,
    "miejsceMontazu" TEXT,
    "lancuchy" TEXT,
    "licznikLokalizacja" TEXT,
    "zasiegInternetu" TEXT,
    "dwieKreski" TEXT,
    "odgromowa" TEXT,
    "numerDzialki" TEXT,
    "mocPrzylaczeniowa" TEXT,
    "zabezpieczenie" TEXT,
    "fazowa" TEXT,
    "taryfa" TEXT,
    "numerLicznika" TEXT,
    "numerPpm" TEXT,
    "cenaBrutto" DOUBLE PRECISION NOT NULL,
    "pierwszaWplata" DOUBLE PRECISION NOT NULL,
    "sposobPlatnosci1" TEXT NOT NULL,
    "czyJednaWplata" TEXT NOT NULL,
    "drugaWplata" DOUBLE PRECISION,
    "sposobPlatnosci2" TEXT,
    "powierzchniaDomu" TEXT,
    "uwagiHandlowca" TEXT,
    "banerZamontowany" TEXT,
    "handlowiecWynagrodzenie" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "Umowa_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Umowa_numerUmowy_key" ON "Umowa"("numerUmowy");

-- AddForeignKey
ALTER TABLE "Umowa" ADD CONSTRAINT "Umowa_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
